name: GitHub README STATS

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 * * *"
  push:
    branches:
      - main

env:
  GITHUB_NAME: Abirdcfly
  GITHUB_EMAIL: fp544037857@gmail.com
  
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: My GitHub Status
        uses: Abirdcfly/github-readme-stats@main
        with:
          WITH_REPOS: false
          WITH_STARED: false
      - name: Push README
        run: |
          git config --local user.email "${{ env.GITHUB_EMAIL }}"
          git config --local user.name "${{ env.GITHUB_NAME }}"
          git commit -a -m 'docs: update readme.md' || echo "nothing to commit"
          git push || echo "nothing to push"
